### ISSUE TITLE
Errors are not handled in tests

### ISSUE THREAD

**Issue by mrmlnc** [posthtml/posthtml-expressions#35]
## Details

We have a few tests with errors, for example:

```js
test('Loops - expression error', (t) => {
  return error('loop_expression_error', (err) => {
    t.truthy(err.toString() === 'SyntaxError: Unexpected token ILLEGAL')
  })
})
```

I change the expected line:

```js
    t.truthy(err.toString() === 'SyntaxError: Unexpected WHAT?!?!?! token ILLEGAL')
```

And then I run tests:

![image](https://cloud.githubusercontent.com/assets/7034281/20919292/1c488ea8-bbac-11e6-97ed-cc15eb3d08d5.png)

## Environment

| OS              | Node      | npm       | PostHTML  |
|:---------------:|:---------:|:---------:|:---------:|
| Windows@10 | 7.2.0 | 3.10.9 | 0.9.1 |

**Comment by mrmlnc** [comment]
Small clarification: PostHTML does not throw exceptions for errors.

**Comment by michael-ciniawsky** [comment]
> PostHTML does not throw exceptions for errors

I'm working on a proposal which gors in the direction PostCSS takes

**plugins.js**
```js
export default posthtmlPlugin (options) {
  return (tree) =>  {
      tree.error(plugin, node, message) // { type: 'error', plugin: 'name', msg: '' }
      tree.warn(plugin, node, message) // { type: 'warning', plugin: 'name', msg: '' }
      tree.add(file) //  // { type: 'dependency', file: '' }

      console.log(tree.messages) // []
  }
}
```

**posthtml.js**
```js
posthtml(plugins).process(file, options).then((result) => {
  result.html = {String}
  result.messages = []
})
```


**reporter.js**
```js
import chalk form 'chalk'
import notify from 'node-notify'

export default posthtmlPlugin (options) {
  options = assign({ notify : false }, options)

  return (tree) =>  {
      tree.messages.forEach((msg) => {
         if (msg.type === 'error') chalk.bold.red(msg)
         if (msg.type === 'warning') chalk.bold.yellow(msg)
      })
      
      if (options.notify) notify({...})
  }
}
```

- Since the  PostHTML Tree gets rextended with the Tree API between each plugin call, we need to save the messages and add the Message API to the extend function.
- Location Info on the nodes is also very important, but the AST refactoring is a highly disliked topic, which needs it's on efforts and focus, if the Message API works, we can think about that separatly😛 
- Also Reshape as very good error handling, which we should consider as blueprint.

**Comment by michael-ciniawsky** [comment]
Any other ideas/approaches highly welcome, I will make PR with the early draft to Core soon and discussion should maybe take place their (or in the respective issue(s) @posthtml/posthtml)

**Comment by michael-ciniawsky** [comment]
@mrmlnc Can we close this one here and continue discussion at posthtml/core?

**Comment by mrmlnc** [comment]
@michael-ciniawsky,Yeap, of course 👌
