### ISSUE TITLE
[Feature Request] If Exists

### ISSUE THREAD

**Issue by shanejones** [posthtml/posthtml-expressions#79]
We already have this for conditional.
```
<if condition="foo === 'bar'">
  <p>Foo really is bar! Revolutionary!</p>
</if>
```

I'm trying to check if a variable exists before outputting it or hiding the block completely if it doesn't exist so I tried 
```
<if condition="foo !== ''">
  <p>Foo really is bar! Revolutionary!</p>
</if>
```

I think it would be great if we had something like 

```
<if exists="foo">
  <p>Foo really is bar! Revolutionary!</p>
</if>
```

**Comment by cossssmin** [comment]
What would `exists` check for, exactly? 

For example, you might check if it's `undefined` and not show the contents, but that's isn't very reliable since it can be defined as a falsy value (`null`, `false`, `0`, etc).

I think it's better left to the user to do the check, so one can check for exactly the type they want. 

@Scrum?

**Comment by Scrum** [comment]
Hi, in theory, any value will be converted to boolean at execution
https://github.com/posthtml/posthtml-expressions/blob/77aaf5696593e7cd14ea41a6505e1f2d03ae8c6e/lib/index.js#L221

try
```html
<if condition="foo">
  <p>Foo really is bar! Revolutionary!</p>
</if>
```
