### ISSUE TITLE
Delimiters: `SyntaxError: Invalid regular expression: Unterminated character class`

### ISSUE THREAD

**Issue by andrhamm** [posthtml/posthtml-expressions#88]
## Problem

Updated from 1.3.2 to 1.4.2 and now starting to see this error. I'm using square brackets in my delimiters (my files contain liquid tags that would conflict with the default delimiters), which are not being escaped properly, causing issues with the Regex used under the hood to find all tags.

Update: I have tested and have confirmed that there is no error in 1.4.0 and that the regression was introduced in 1.4.1.

## Details

options used:

```
delimiters: ['%[', ']%'],
unescapeDelimiters: ['%[[', ']]%'],
```

## Error Logs

```
SyntaxError: Invalid regular expression: /@%[/: Unterminated character class
```

Stack trace [here](https://gist.github.com/andrhamm/c37499d160e21344974be3d849f9140a)

## Environment

| OS              | Node      | npm       | PostHTML  |
|:---------------:|:---------:|:---------:|:---------:|
| macOS 10.15.5   | v14.3.0   | 1.4.2     | 0.12.3    |

**Comment by cossssmin** [comment]
Indeed, it fails here:

https://github.com/posthtml/posthtml-expressions/blob/b351d16e02a751c357404691677578aafb613cdb/lib/index.js#L151

... because the resulting delimiter regex `@%[` is invalid (Unmatched opening square bracket).

The opening string delimiter needs to be properly handled for use in a regex (escaped). 

I'll work on a fix for this, but meanwhile know that you can use `@{{ }}` to ignore expression parsing, so you can keep using Liquid tags and have `{{ }}` output in the compiled code.

**Comment by andrhamm** [comment]
@cossssmin Thank you for the quick response. I find the `@{{` syntax troubling because it doesn't stand out as much from the Liquid tags when reviewing code, and also would potentially cause problems in cases where you might be rendering a dynamic username or email address in Liquid. i.e. (this is valid liquid but would be interpreted as expressions, I believe):

		My Twitter is: @{{username}}

		My email is: {{username}}@{{domain}}

I'll stay on an old version for now 👍

**Comment by cossssmin** [comment]
It'll work fine. Given `username` is provided in `locals` and is equal to, say, `admin`, then this:

```
{{username}}@{{domain}}
```

... will result in:

```
admin{{domain}}
```
